[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NEXT_PRIVATE_TARGET = "server"
  PYTHON_VERSION = "3.11.7"
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"
